// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq_iXvJ8jYBPSlH1SIVNYHod01zKcZzWk',
    appId: '1:43949110941:web:3d356d94c1de5aef9b8674',
    messagingSenderId: '43949110941',
    projectId: 'ecommerce-flutter-app-dd82a',
    authDomain: 'ecommerce-flutter-app-dd82a.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-dd82a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmznqhLiBbhUkX1RCt5W2mzgcN6deGyVo',
    appId: '1:43949110941:android:da7a0e3fd42ec2169b8674',
    messagingSenderId: '43949110941',
    projectId: 'ecommerce-flutter-app-dd82a',
    storageBucket: 'ecommerce-flutter-app-dd82a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2P4VfH4A5vP5WnRYqqBJNiUY-REoHvQ0',
    appId: '1:43949110941:ios:29dbbd0a63b3caf69b8674',
    messagingSenderId: '43949110941',
    projectId: 'ecommerce-flutter-app-dd82a',
    storageBucket: 'ecommerce-flutter-app-dd82a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2P4VfH4A5vP5WnRYqqBJNiUY-REoHvQ0',
    appId: '1:43949110941:ios:29dbbd0a63b3caf69b8674',
    messagingSenderId: '43949110941',
    projectId: 'ecommerce-flutter-app-dd82a',
    storageBucket: 'ecommerce-flutter-app-dd82a.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq_iXvJ8jYBPSlH1SIVNYHod01zKcZzWk',
    appId: '1:43949110941:web:d9947f3723d4e6da9b8674',
    messagingSenderId: '43949110941',
    projectId: 'ecommerce-flutter-app-dd82a',
    authDomain: 'ecommerce-flutter-app-dd82a.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-dd82a.firebasestorage.app',
  );

}