// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_GXiZN-f0BU0jhfQbdR17Cdg281Gsih0',
    appId: '1:116423029040:web:8e9288ef9db41aa44398f5',
    messagingSenderId: '116423029040',
    projectId: 'ecommerce-flutter-app-76602',
    authDomain: 'ecommerce-flutter-app-76602.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-76602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5wH0GoOXkRB91m3GeruH1hxVTr80T9E',
    appId: '1:116423029040:android:c482699422bdc3d94398f5',
    messagingSenderId: '116423029040',
    projectId: 'ecommerce-flutter-app-76602',
    storageBucket: 'ecommerce-flutter-app-76602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4a4gfzJURESCGquyqhyigeGRhIJnTSM',
    appId: '1:116423029040:ios:6b954d61c6d1ca3c4398f5',
    messagingSenderId: '116423029040',
    projectId: 'ecommerce-flutter-app-76602',
    storageBucket: 'ecommerce-flutter-app-76602.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4a4gfzJURESCGquyqhyigeGRhIJnTSM',
    appId: '1:116423029040:ios:6b954d61c6d1ca3c4398f5',
    messagingSenderId: '116423029040',
    projectId: 'ecommerce-flutter-app-76602',
    storageBucket: 'ecommerce-flutter-app-76602.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_GXiZN-f0BU0jhfQbdR17Cdg281Gsih0',
    appId: '1:116423029040:web:0550ae51da024b1b4398f5',
    messagingSenderId: '116423029040',
    projectId: 'ecommerce-flutter-app-76602',
    authDomain: 'ecommerce-flutter-app-76602.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-app-76602.firebasestorage.app',
  );
}
